#!/usr/bin/env node
/**
 * Assemble ds-bundle/ — the upload payload for the Polaris design system in
 * Claude Design (claude.ai/design).
 *
 * Polaris has no component library, so this is deliberately NOT the /design-sync
 * converter: there is no dist/, no window global, no .d.ts. What the design agent
 * receives is the real stylesheet plus a conventions README that teaches it the
 * class vocabulary, and a set of hand-authored preview cards.
 *
 * Sources (all committed):
 *   design/css/*.css            the kit, copied verbatim — never edited here
 *   .design-sync/conventions.md the conventions header, prepended to the README
 *   .design-sync/cards/         authored preview cards, copied to components/
 *
 * Run from the repo root:  node .design-sync/build.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, cpSync, rmSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const out = join(repo, 'ds-bundle');

rmSync(out, { recursive: true, force: true });
mkdirSync(join(out, 'css'), { recursive: true });

// 1. The kit, verbatim.
for (const f of ['polaris-ui.css', 'polaris-mobile.css']) {
  cpSync(join(repo, 'design', 'css', f), join(out, 'css', f));
}

// 2. The entry point. Rendered designs receive only this file's @import closure,
//    so the fonts and the kit must both be reachable from here.
writeFileSync(join(out, 'styles.css'), `/* ─────────────────────────────────────────────────────────────────────────────
   Polaris UI — design-system entry point.  GENERATED by .design-sync/build.mjs.

   Everything a rendered design receives comes through THIS file's @import
   closure, so the brand fonts and the kit stylesheet are both pulled in here.
   Do not edit css/polaris-ui.css: it is a verbatim copy of the Polaris kit.
   Add new rules in a separate sheet loaded after this one.
   ───────────────────────────────────────────────────────────────────────── */

/* Brand faces. Inter carries all UI text; Roboto Mono carries every identifier
   (IPs, MACs, serials, IDs) via the .mono class and --font-mono. */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Roboto+Mono:wght@400;500;700&display=swap');

/* The kit: tokens, the three themes, and every component class. */
@import url('./css/polaris-ui.css');

/* Phone surface. Polaris treats mobile as a separate app rather than a
   responsive desktop, so this sheet is only relevant to phone-shaped designs. */
@import url('./css/polaris-mobile.css');
`);

// 3. Authored preview cards.
cpSync(join(here, 'cards'), join(out, 'components'), { recursive: true });

// 4. README = conventions header + an index of what shipped.
function walk(dir) {
  const r = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) r.push(...walk(p));
    else if (e.endsWith('.html')) r.push(p);
  }
  return r;
}
const cards = walk(join(out, 'components')).map((f) => {
  const rel = f.slice(out.length + 1).replace(/\\/g, '/');
  const html = readFileSync(f, 'utf8');
  const group = html.match(/@dsCard\s+group="([^"]+)"/)?.[1] ?? 'Components';
  const title = html.match(/<title>([\s\S]*?)<\/title>/)?.[1].trim() ?? rel;
  return { rel, group, title };
});

const byGroup = new Map();
for (const c of cards) {
  if (!byGroup.has(c.group)) byGroup.set(c.group, []);
  byGroup.get(c.group).push(c);
}

const index = [...byGroup.entries()]
  .map(([group, items]) =>
    `### ${group}\n\n` + items.map((i) => `- **${i.title}** — \`${i.rel}\``).join('\n'))
  .join('\n\n');

const header = readFileSync(join(here, 'conventions.md'), 'utf8').trimEnd();

writeFileSync(join(out, 'README.md'), `${header}

---

## What is in this project

\`styles.css\` is the entry point; everything else it needs is in its \`@import\`
closure. \`css/polaris-ui.css\` is a verbatim copy of the Polaris kit — the same file
the application itself serves — so it is authoritative, not a summary.

The preview cards below are static HTML rendered with that stylesheet. They are
reference markup: copy from them directly.

${index}

_Generated by \`.design-sync/build.mjs\` from \`design/\`. Do not edit files in
\`ds-bundle/\` by hand — edit the sources and rebuild._
`);

console.log(`ds-bundle/ built — ${cards.length} cards, ${byGroup.size} groups`);
